#https://github.com/edbizarro/gitlab-ci-pipeline-php
#https://github.com/ohdearapp/gitlab-ci-pipeline-for-laravel/blob/master/.gitlab-ci.
#http://www.obsis.unb.br/gitlab/help/ci/examples/laravel_with_gitlab_and_envoy/index.md

image: edbizarro/gitlab-ci-pipeline-php:7.4-chromium

services:
  - mysql:5.7

variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: blogdb
    DB_HOST: mysql
    DB_USERNAME: root

stages:
  - preparation
  - codesniffer
  - testing
  - deploying
  

composer:
  stage: preparation
  script:
    - mysql --version
    - curl -LO https://deployer.org/deployer.phar
    - sudo mv deployer.phar /usr/local/bin/dep
    - sudo chmod +x /usr/local/bin/dep
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - dep --version
  artifacts:
    paths:
      - vendor
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/


psr2:
  stage: codesniffer
  dependencies:
    - composer
  script:
    - php -v
    - ./vendor/bin/phpcs

 
phpunit:
  stage: testing
  dependencies:
    - psr2
    - composer
  script:
    - php -v
    - php artisan dusk:chrome-driver 
    - php artisan migrate
    - ./vendor/phpunit/phpunit/phpunit --version
    - php artisan serve &
    - ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
    - sleep 5
    - php artisan dusk
  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots # for Dusk screenshots
      - ./tests/Browser/console
    expire_in: 1 days
    when: on_failure

deploy:
  stage: deploying
  dependencies:
    - composer
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - dep deploy production --tag=$CI_COMMIT_REF_NAME -vvv
  only:
    - main
