stages:
  - preparation
  - building
  - testing
  - security

image: edbizarro/gitlab-ci-pipeline-php:7.4-chromium

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: blogdb
  DB_HOST: 127.0.0.1



cache:
  key: $CI_BUILD_REF_NAME 

composer:
  stage: preparation
  services:
    - mysql:5.7
  script:
    - mysql --version
    - yarn config set cache-folder .yarn
    - yarn install --pure-lockfile
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --no-suggest
    - cp .env.example .env
    - php artisan migrate:refresh --seed
  artifacts:
    paths:
      - vendor
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

yarn:
  stage: preparation
  script:
    - yarn install --pure-lockfile
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 days
    when: always
  cache:
    paths:
    - node_modules/


phpunit:
  stage: testing
  services:
    - name: mysql:5.7      
  
  dependencies:
    - composer
  script:
    - php -v
    - php artisan dusk:chrome-driver 
    - ./vendor/phpunit/phpunit/phpunit --version
    - php artisan serve &
    - ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
    - sleep 5
    - php artisan dusk
  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots # for Dusk screenshots
      - ./tests/Browser/console
    expire_in: 1 days
    when: on_failure