#https://github.com/edbizarro/gitlab-ci-pipeline-php
#https://github.com/ohdearapp/gitlab-ci-pipeline-for-laravel/blob/master/.gitlab-ci.
#http://www.obsis.unb.br/gitlab/help/ci/examples/laravel_with_gitlab_and_envoy/index.md

image: edbizarro/gitlab-ci-pipeline-php:7.4-chromium

services:
  - mysql:5.7

variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: blogdb
    DB_HOST: mysql
    DB_USERNAME: root

stages:
  - preparation
  - building
  - testing
  - security

composer:
  stage: preparation
  script:
    - mysql --version
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
  artifacts:
    paths:
      - vendor
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

yarn:
  stage: preparation
  script:
    - yarn install --pure-lockfile
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 days
    when: always
  cache:
    paths:
    - node_modules/


phpunit:
  stage: testing
  services:
    - mysql:5.7      
  image: edbizarro/gitlab-ci-pipeline-php:7.4-chromium
  dependencies:
    - composer
  script:
    - php -v
    - php artisan dusk:chrome-driver 
    - ./vendor/phpunit/phpunit/phpunit --version
    - php artisan serve &
    - ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
    - sleep 5
    - php artisan dusk
  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots # for Dusk screenshots
      - ./tests/Browser/console
    expire_in: 1 days
    when: on_failure