image: registry.gitlab.com/glaucotodesco/laravel-blogdb:latest

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: blogdb
  MYSQL_ROOT_PASSWORD: root
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test
  
unit_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit