name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:

    - uses: atymic/deployer-php-action@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Deploy to Prod
      env:
        DOT_ENV: ${{ secrets.DOT_ENV }}
      run: dep deploy --tag=${{ env.GITHUB_REF }} -vvv      
      
      
      
